# Generated by Django 5.0.6 on 2026-01-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliverySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[("DELIVERY_FEE_FLAT", "Delivery fee flat")],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_auditl_entity_6d919a_idx",
            old_name="core_audit_entity_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_auditl_created_dc23ea_idx",
            old_name="core_audit_created_idx",
        ),
        migrations.AddIndex(
            model_name="deliverysetting",
            index=models.Index(fields=["key"], name="core_delive_key_b1e79a_idx"),
        ),
    ]
